name = "fast-search"
compatibility_date = "2024-04-08"

[vars]
UPSTASH_REDIS_REST_URL="https://pure-cobra-49000.upstash.io"
UPSTASH_REDIS_REST_TOKEN="Ab9oASQgMDFmYmYwMDItN2IzYi00NzkyLWFmOGItMTViNzc2Mzg3YmYwZjk1MmU5ODE3MGFkNGUxMWFhODlhNDcyZTU5MjQ4M2U="